services:
#   mongo-db:
#      image: "mongo"
#      environment:
#         - MONGO_INITDB_ROOT_USERNAME=sa_fenix
#         - MONGO_INITDB_ROOT_PASSWORD=mJFWwVN&aEbSvs8
#      ports:
#         - "22110:27017"
#      container_name: mongo-db-prod
#      volumes:
#         - ${MONGO_DATA_DIR}:/data/db
#      networks:
#         - fenix-docker-network
#      hostname: mongodb
   defect-record-web:
      build:
         context: ../defect_record_web
         dockerfile: Dockerfile
      image: "defect_record_web"
      ports:
         - "22111:80"
      container_name: defect_record_web
      networks:
         - defect-docker-network
   defect-record-service:
      build:
         context: ../.
         dockerfile: defect_record_backend/Dockerfile
      image: "defect-record-service"
      ports:
         - "32110:32110"
      container_name: defect-record-service
      networks:
         - defect-docker-network
      hostname: defect-record-service
      stdin_open: true
      tty: true
      restart: on-failure:5
      mem_limit: 3g
networks:
   defect-docker-network: {}