services:
   mongo-db:
      image: "mongo"
      environment:
         - MONGO_INITDB_ROOT_USERNAME=sa_fenix
         - MONGO_INITDB_ROOT_PASSWORD=mJFWwVN&aEbSvs8
      ports:
         - "40000:27017"
      container_name: mongo-db-defect
      volumes:
         - /home/safra/services/databases/mongo-defect:/data/db
      networks:
         - defect-docker-network
      hostname: mongodb
   defect-record-web:
      build:
         context: ../defect_record_front
         dockerfile: Dockerfile
      image: "defect_record_front"
      ports:
         - "42111:80"
      container_name: defect_record_front
      networks:
         - defect-docker-network
   defect-record-service:
      build:
         context: .
         dockerfile: Dockerfile
      image: "defect-record-service"
      ports:
         - "42111:22110"
      container_name: defect-record-service
      networks:
         - defect-docker-network
      hostname: defect-record-service
      stdin_open: true
      tty: true
      restart: on-failure:5
      mem_limit: 3g
networks:
   defect-docker-network: {}